//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildAppAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userContacts
    {
        public string email { get; set; }
        public string father { get; set; }
        public string mother { get; set; }
        public string friend { get; set; }
    }
}
