//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildAppAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string childage { get; set; }
        public string childcheckbox { get; set; }
        public string gardenname { get; set; }
        public string password { get; set; }
        public string birthdate { get; set; }
    }
}
